In [1]:
import sympy as sp

# Define symbolic variables
x, y = sp.symbols('x, y')

# Define a vector field function
u = sp.sin(3.2*x*(x - y))*sp.cos(4.3*y + x) + sp.sin(4.6*(x + 2*y))*sp.cos(2.6*(y - 2*x))

mu=1

print(mu)

sigma=0

print(sigma)

beta1=0
beta2=0

print(beta1)

1
0
0


In [2]:
# Calculate the gradient
ux = sp.diff(u, x)
uy = sp.diff(u, y)

f1x = sp.diff(mu*ux,x)
f1y = sp.diff(mu*uy,y)
f_mu = - f1x - f1y
f_beta = beta1*ux + beta2*uy
f_sigma = sigma*u

f = f_mu + f_beta + f_sigma


In [3]:
# Display the results
print("Solution:", u)
print("Gradient in x:", ux)
print("Gradient in y:", uy)
print("f:", f)

Solution: sin(3.2*x*(x - y))*cos(x + 4.3*y) + sin(4.6*x + 9.2*y)*cos(5.2*x - 2.6*y)
Gradient in x: (6.4*x - 3.2*y)*cos(3.2*x*(x - y))*cos(x + 4.3*y) - sin(3.2*x*(x - y))*sin(x + 4.3*y) - 5.2*sin(4.6*x + 9.2*y)*sin(5.2*x - 2.6*y) + 4.6*cos(4.6*x + 9.2*y)*cos(5.2*x - 2.6*y)
Gradient in y: -3.2*x*cos(3.2*x*(x - y))*cos(x + 4.3*y) - 4.3*sin(3.2*x*(x - y))*sin(x + 4.3*y) + 2.6*sin(4.6*x + 9.2*y)*sin(5.2*x - 2.6*y) + 9.2*cos(4.6*x + 9.2*y)*cos(5.2*x - 2.6*y)
f: 10.24*x**2*sin(3.2*x*(x - y))*cos(x + 4.3*y) - 27.52*x*sin(x + 4.3*y)*cos(3.2*x*(x - y)) + (40.96*(x - 0.5*y)**2)*sin(3.2*x*(x - y))*cos(x + 4.3*y) + 2*(6.4*x - 3.2*y)*sin(x + 4.3*y)*cos(3.2*x*(x - y)) + 19.49*sin(3.2*x*(x - y))*cos(x + 4.3*y) + 139.6*sin(4.6*x + 9.2*y)*cos(5.2*x - 2.6*y) - 6.4*cos(3.2*x*(x - y))*cos(x + 4.3*y)


In [8]:
n = mu*uy
print(n)

(sin(x + 2*y) + 2)*(-3.2*x*cos(3.2*x*(x - y))*cos(x + 4.3*y) - 4.3*sin(3.2*x*(x - y))*sin(x + 4.3*y) + 2.6*sin(4.6*x + 9.2*y)*sin(5.2*x - 2.6*y) + 9.2*cos(4.6*x + 9.2*y)*cos(5.2*x - 2.6*y))


In [ ]:
tf.Tensor(
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-1.69867579] [-1.69798944]
 [-0.72332437] [-0.72420933]
 [-0.45929179] [-0.46061086]
 [-1.16697545] [-1.16683271]
 [-1.79000199] [-1.78844783]
 [-1.46057122] [-1.45978791]
 [-0.87713464] [-0.87850542]
 [ 0.        ] [ 0.        ]
 [ 0.        ] [ 0.        ]
 [ 0.        ] [ 0.        ]
 [ 0.        ] [ 0.        ]
 [ 0.        ] [ 0.        ]
 [ 0.        ] [ 0.        ]
 [ 0.        ] [ 0.        ]
 [-0.94449268] [-0.94316852]
 [-0.09250868] [-0.09256636]
 [ 0.68025207] [ 0.67874342]
 [ 0.35500448] [ 0.35404042]
 [-0.52900065] [-0.52801959]
 [-0.47453474] [-0.47283486]
 [ 0.98090301] [ 0.98102925]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]], shape=(145, 1), dtype=float64)

In [ ]:
tf.Tensor(
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-1.69798944]
 [-0.72420933]
 [-0.46061086]
 [-1.16683271]
 [-1.78844783]
 [-1.45978791]
 [-0.87850542]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.94316852]
 [-0.09256636]
 [ 0.67874342]
 [ 0.35404042]
 [-0.52801959]
 [-0.47283486]
 [ 0.98102925]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]], shape=(145, 1), dtype=float64)

In [6]:
import numpy as np
temp1 = np.reshape([0,1,2], (-1,1))
temp2 = np.reshape([2,3,4], (-1,1))
temp3 = np.concatenate([temp1, temp2], axis=1)

print(temp3)

[[0 2]
 [1 3]
 [2 4]]
