In [1]:
import tensorflow as tf 

2023-11-16 16:50:41.331302: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-16 16:50:41.332745: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-16 16:50:41.367635: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-16 16:50:41.368989: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-16 16:50:42.005152: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Co

In [83]:
import tensorflow as tf

# Define the function f(x) = x A x^T
A = tf.constant([[1.0, 2.0]], dtype=tf.float32)
def f(x,A):

    return tf.sin(x@tf.transpose(A))  # Ax vector classic


# Generate some input data
x = tf.Variable([[1.0,2.0]])


print('eval',f(x,A))
print('der_eval',A*tf.cos(x@tf.transpose(A)))


with tf.GradientTape() as tape:
    tape.watch(x)
    res=f(x,A)
der=tape.gradient(res,x)

print('tf_der',der)






eval tf.Tensor([[-0.9589243]], shape=(1, 1), dtype=float32)
der_eval tf.Tensor([[0.2836622 0.5673244]], shape=(1, 2), dtype=float32)
tf_der tf.Tensor([[0.2836622 0.5673244]], shape=(1, 2), dtype=float32)


In [87]:
import tensorflow as tf

# Define the function f(x) = x A x^T
A = tf.constant([[1.0, 2.0]], dtype=tf.float32)
def f(x,A):

    return tf.sin(x@tf.transpose(A))  # Ax vector classic


# Generate some input data
x = tf.Variable([[1.0,2.0]])
y= tf.Variable([[5.0,7.0]])



print('eval x',f(x,A))
print('der_eval x',A*tf.cos(x@tf.transpose(A)))

print('eval y',f(y,A))
print('der_eval x',A*tf.cos(y@tf.transpose(A)))



print()
with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    tape.watch(y)
    resx=f(x,A)
    resy=f(y,A)
    
derx=tape.gradient(resx,x)
dery=tape.gradient(resy,y)


print('tf_der x',derx)
print('tf_der y',dery)

eval x tf.Tensor([[-0.9589243]], shape=(1, 1), dtype=float32)
der_eval x tf.Tensor([[0.2836622 0.5673244]], shape=(1, 2), dtype=float32)
eval y tf.Tensor([[0.1498772]], shape=(1, 1), dtype=float32)
der_eval x tf.Tensor([[0.9887046 1.9774092]], shape=(1, 2), dtype=float32)

tf_der x tf.Tensor([[0.2836622 0.5673244]], shape=(1, 2), dtype=float32)
tf_der y tf.Tensor([[0.9887046 1.9774092]], shape=(1, 2), dtype=float32)


In [97]:
import tensorflow as tf

# Define the function f(x) = x A x^T
A = tf.constant([[1.0, 2.0]], dtype=tf.float32)

def f(x,A):

    return tf.sin(x@tf.transpose(A))  # Ax vector classic


# Generate some input data
v = tf.Variable([[[1.0,2.0],[5.0,7.0],[3.0,7.0]],[[1.0,2.0],[5.0,7.0],[3.0,7.0]]])

print(tf.cos(v@tf.transpose(A)))

print('eval ',f(v,A))
print('der_eval ',A*tf.cos(v@tf.transpose(A)))



print()
with tf.GradientTape(persistent=True) as tape:
    tape.watch(v)
    res=f(v,A)
    
    der=tape.gradient(res,v)
derder=tape.gradient(der,v)


print('tf_der',der)


print()




tf.Tensor(
[[[ 0.2836622 ]
  [ 0.9887046 ]
  [-0.27516335]]

 [[ 0.2836622 ]
  [ 0.9887046 ]
  [-0.27516335]]], shape=(2, 3, 1), dtype=float32)
eval  tf.Tensor(
[[[-0.9589243 ]
  [ 0.1498772 ]
  [-0.96139747]]

 [[-0.9589243 ]
  [ 0.1498772 ]
  [-0.96139747]]], shape=(2, 3, 1), dtype=float32)
der_eval  tf.Tensor(
[[[ 0.2836622   0.5673244 ]
  [ 0.9887046   1.9774092 ]
  [-0.27516335 -0.5503267 ]]

 [[ 0.2836622   0.5673244 ]
  [ 0.9887046   1.9774092 ]
  [-0.27516335 -0.5503267 ]]], shape=(2, 3, 2), dtype=float32)

tf_der tf.Tensor(
[[[ 0.2836622   0.5673244 ]
  [ 0.9887046   1.9774092 ]
  [-0.27516335 -0.5503267 ]]

 [[ 0.2836622   0.5673244 ]
  [ 0.9887046   1.9774092 ]
  [-0.27516335 -0.5503267 ]]], shape=(2, 3, 2), dtype=float32)

