In [2]:
import tensorflow as tf 


2023-11-18 01:51:09.613504: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-18 01:51:09.615453: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-18 01:51:09.651462: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-18 01:51:09.652191: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-18 01:51:10.592805: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Co

In [10]:
x=tf.Variable(1.0,dtype=tf.float64)
w=tf.Variable(3.0,dtype=tf.float64)
y=tf.constant(4.0,dtype=tf.float64)

output=tf.Variable(tf.zeros((10,1),dtype=tf.float64))

In [57]:
#net
def f(x,w):
    return tf.sin(w*x)

def grad(x):
    with tf.GradientTape() as tape:
        tape.watch(x)
        res=f(x,w)
    return tape.gradient(res,x),res  #=w*tf.cos(x)

w*tf.cos(w*x)

<tf.Tensor: shape=(), dtype=float64, numpy=-2.9699774898013365>

In [45]:
grad(x)

<tf.Tensor: shape=(), dtype=float64, numpy=-2.9699774898013365>

In [58]:
def loss():
    der,res=grad(x)
    
    return der+res


In [59]:
with tf.GradientTape() as tape:
  loss_function=loss()
tape.gradient(loss_function,w)  # tf.cos(w*x)-x*tf.sin(w*x)

<tf.Tensor: shape=(), dtype=float64, numpy=-2.4033450173804924>

In [46]:
tf.cos(w*x)-w*x*tf.sin(x*w)

<tf.Tensor: shape=(), dtype=float64, numpy=-1.413352520780047>

In [61]:
tf.reduce_sum([5,6])

<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [17]:
indices = tf.constant([[4], [3], [1], [7]])
updates = [9, 10, 11, 12]
shape = [8]
scatter = tf.scatter_nd(indices, updates, shape)
scatter_=tf.expand_dims(scatter,axis=1)
print(scatter_)

tf.Tensor(
[[ 0]
 [11]
 [ 0]
 [10]
 [ 9]
 [ 0]
 [ 0]
 [12]], shape=(8, 1), dtype=int32)


In [1]:
import tensorflow as tf

# Example for-loop
num_iterations = 10
sum_of_vectors = tf.zeros((5,))  # Assuming vectors of length 5

for i in range(num_iterations):
    # Replace this with your logic to create vector vi for each iteration
    vi = tf.constant([float(i), float(i + 1), float(i + 2), float(i + 3), float(i + 4)])
    
    # Accumulate the vectors
    sum_of_vectors += vi

# Print the sum of vectors
print("Sum of Vectors:", sum_of_vectors.numpy())

2023-11-18 02:10:57.789883: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-18 02:10:57.791297: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-18 02:10:57.824431: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-18 02:10:57.825206: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-18 02:10:58.499510: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Co

Sum of Vectors: [45. 55. 65. 75. 85.]
