In [1]:
import tensorflow as tf 


2023-11-18 12:03:21.458281: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-18 12:03:21.484833: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-18 12:03:21.693932: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-18 12:03:21.695422: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-18 12:03:22.721051: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Co

In [13]:
x=tf.constant(1.0,dtype=tf.float64)
w=tf.Variable(3.0,dtype=tf.float64)
out=tf.Variable(0.0,dtype=tf.float64)


y=tf.constant(4.0,dtype=tf.float64)

output=tf.Variable(tf.zeros((10,1),dtype=tf.float64))

In [83]:
#net
def f(x,w):
    return tf.sin(w*x)


sum=tf.Variable(tf.zeros((10,1),dtype=tf.float64))
print(sum)

def grad(x,sum):
    with tf.GradientTape() as tape:
        tape.watch(x)
        res=f(x,w)

        print('res : ',res)
        print()
        
        for ii in range(2):

            indices = tf.constant([[0+ii, 0], [3+ii, 0], [8+ii, 0]], dtype=tf.int64)

            #sum=tf.reduce_sum([[res,2.0*res,3.0*res]],axis=0)
            #sum=tf.constant([res,2.0*res,3.0*res],dtype=tf.float64)

            print(sum)

            dense_shape = tf.constant([10, 1], dtype=tf.int64)


            scatter = tf.sparse.SparseTensor(indices=indices, values=[res,2.0*res,3.0*res], dense_shape=dense_shape)
            print('scatter : ',scatter)
            print()
            print('dense : ',tf.sparse.to_dense(scatter))

            #scatter_=tf.expand_dims(scatter,axis=1)

            #new=tf.sparse.reduce_sum(scatter)
            print('scatterrrrrrrrrrrrrrrrrrrrrr',scatter)
            break
            sum=tf.sparse.add(scatter,sum)

    print(sum)
    return tape.gradient(sum,x)  #=w*tf.cos(w*x)

print(6*w*tf.cos(w*x))
print()

print(grad(x,sum))

<tf.Variable 'Variable:0' shape=(10, 1) dtype=float64, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])>
tf.Tensor(-17.819864938808017, shape=(), dtype=float64)

res :  tf.Tensor(0.1411200080598672, shape=(), dtype=float64)

<tf.Variable 'Variable:0' shape=(10, 1) dtype=float64, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])>
scatter :  SparseTensor(indices=tf.Tensor(
[[0 0]
 [3 0]
 [8 0]], shape=(3, 2), dtype=int64), values=tf.Tensor([0.14112001 0.28224002 0.42336002], shape=(3,), dtype=float64), dense_shape=tf.Tensor([10  1], shape=(2,), dtype=int64))

dense :  tf.Tensor(
[[0.14112001]
 [0.        ]
 [0.        ]
 [0.28224002]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.42336002]
 [0.        ]], shape=(10, 1), dtype=float64)
scatterrrrrrrrrrrrrrrrrrrrrr SparseTensor(indices=tf.Tensor(
[[0 0]

In [51]:
indices = tf.constant([[0, 0], [1, 0], [9, 0]], dtype=tf.int64)
values = tf.constant([1.0, 2.0, 3.0], dtype=tf.float32)
dense_shape = tf.constant([10, 1], dtype=tf.int64)

sparse_tensor = tf.sparse.SparseTensor(indices=indices, values=values, dense_shape=dense_shape)


print(sparse_tensor)

print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 0]
 [9 0]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([10  1], shape=(2,), dtype=int64))
tf.Tensor(
[[1.]
 [2.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [3.]], shape=(10, 1), dtype=float32)


In [45]:
grad(x)

<tf.Tensor: shape=(), dtype=float64, numpy=-2.9699774898013365>

In [58]:
def loss():
    der,res=grad(x)
    
    return der+res


In [59]:
with tf.GradientTape() as tape:
  loss_function=loss()
tape.gradient(loss_function,w)  # tf.cos(w*x)-x*tf.sin(w*x)

<tf.Tensor: shape=(), dtype=float64, numpy=-2.4033450173804924>

In [46]:
tf.cos(w*x)-w*x*tf.sin(x*w)

<tf.Tensor: shape=(), dtype=float64, numpy=-1.413352520780047>

In [61]:
tf.reduce_sum([5,6])

<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [17]:
indices = tf.constant([[4], [3], [1], [7]])
updates = [9, 10, 11, 12]
shape = [8]
scatter = tf.scatter_nd(indices, updates, shape)
scatter_=tf.expand_dims(scatter,axis=1)
print(scatter_)

tf.Tensor(
[[ 0]
 [11]
 [ 0]
 [10]
 [ 9]
 [ 0]
 [ 0]
 [12]], shape=(8, 1), dtype=int32)


In [1]:
import tensorflow as tf

# Example for-loop
num_iterations = 10
sum_of_vectors = tf.zeros((5,))  # Assuming vectors of length 5

for i in range(num_iterations):
    # Replace this with your logic to create vector vi for each iteration
    vi = tf.constant([float(i), float(i + 1), float(i + 2), float(i + 3), float(i + 4)])
    
    # Accumulate the vectors
    sum_of_vectors += vi

# Print the sum of vectors
print("Sum of Vectors:", sum_of_vectors.numpy())

2023-11-18 02:10:57.789883: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-18 02:10:57.791297: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-18 02:10:57.824431: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-18 02:10:57.825206: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-18 02:10:58.499510: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Co

Sum of Vectors: [45. 55. 65. 75. 85.]


In [84]:
v0=1.0
v1=2.0
v2=3.0

v=[v0, v1, v2]*[0.0,0.0,0.0]

TypeError: can't multiply sequence by non-int of type 'list'